### ISSUE TITLE
[termux/termux-packages] Auto update failing for rgbds (Issue #12248)

### ISSUE THREAD

**Issue by Pembasmikalem** [noob-hackers/hacklock#28]
‎❰❰❰❰❰❰❰ᎪᎡᎥᎩᎪᎠᎥ ᎪᏣᎢᎾᎡ ᏴᎯᏁᏀᏚᎯᎢ ᏞᎥᎪᎡ❱❱❱❱❱❱❱ ︻दΩ๏ـــــــــــــــــــــــــــــــــــــــ๏๏๏ ⸙ MAFIA TERDIDIK DI LINDUNG ՁՁち DEWA DEWI RINJAN LOUT NETWORK PENGGUNA ACCOUNT CYBER MUSLIM ANONYMOUS ︻दΩ๏ـــــــــــــــــــــــــــــــــــــــ๏๏๏ ⸙‎

**Comment by hdsh55** [comment]
``
