### ISSUE TITLE
Links are not getting generated 

### ISSUE THREAD

**Issue by khansaad1275** [noob-hackers/hacklock#8]
I am not getting ngrok link, with or without hotspot on. tired 5 times

**Comment by mukulyad** [comment]
I am not getting link with or without hotspot

**Comment by Klavyeli** [comment]
Inside the Hacklock directory, follow these commands; 
* `rm -rf ngrok` 
* `pkg install wget unzip` 
* `wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip`
*  `unzip ngrok-stable-linux-arm.zip` 
* ` chmod +x ngrok`
* `./ngrok authtoken "enter your ngrok token in this field remove the quotes"`
* `bash hacklock.sh`

**Comment by ZekePolarisBSH** [comment]
> Inside the Hacklock directory, follow these commands;
> 
> * `rm -rf ngrok`
> * `pkg install wget unzip`
> * `wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip`
> * `unzip ngrok-stable-linux-arm.zip`
> * ` chmod +x ngrok`
> * `./ngrok authtoken "enter your ngrok token in this field remove the quotes"`
> * `bash hacklock.sh`

I have this other tool that does this same thing with no issues.... Also, it doesn't force us to give them our IP address by them using brandly URLs....

**Comment by Majorposquare** [comment]
What's the name of that tool please

**Comment by ZekePolarisBSH** [comment]
All tools that uses ngrok, for me. Do you know how to fix it? I followed
all steps possibe.
